### ISSUE TITLE
installation issue on creating security group

### ISSUE THREAD

**Issue by jimgros** [StreisandEffect/streisand#1010]
At installation, I get the following error
### Expected behavior:
Continue installation normally
### Actual Behavior:

TASK [ec2-security-group : Create the EC2 security group] **************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_m83gtu/ansible_module_ec2_group.py\", line 899, in <module>\n    main()\n  File \"/tmp/ansible_m83gtu/ansible_module_ec2_group.py\", line 801, in main\n    add_rules_to_lookup(group['IpPermissionsEgress'], group['GroupId'], 'out', groupRules)\n  File \"/tmp/ansible_m83gtu/ansible_module_ec2_group.py\", line 314, in add_rules_to_lookup\n    for ipv6Grants in rule.get('Ipv6Ranges'):\nTypeError: 'NoneType' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/home/jimmy/streisand/playbooks/amazon.retry

### Steps to Reproduce:
1. No clue

no diagnostics.md file

##### *Output from `git rev-parse HEAD` in your Streisand directory : fc0cca533af5efdb69b73c900cb31398067c94d4

Thanks!

**Comment by nopdotcom** [comment]
You might have bumped up against a resource limit in AWS. (Amazon has low limits on some items because people accidentally create them; if you have a need for more, just call them.) Check through your AWS dashboard for dangling resources.

Another possibility is that there is version skew between the Python modules you're using and what we're using. The cheap way to avoid version skew is to install everything in a virtual environment. Here's what I'm using now; it should work on WSL. https://github.com/nopdotcom/streisand/blob/builder-scripts/util/venv-dependencies.sh

**Comment by jimgros** [comment]
Hi Nopdotcom. Thanks for the reply. I'd forgotten I posted it and in the mean time switched to DO instead, which works fine.

**Comment by nopdotcom** [comment]
@jimgros All's well that ends well, they say. Sorry we didn't get back to this sooner, but this is a weekend-centric project sometimes.

Thank you for the bug report: even if we don't have a solution to it, we know there is a pain point there, and when the next person hits it, we can look this up.

If we were really dedicated to EC2 it might be worthwhile to be more resilient to errors like "out of public IP addresses". We aren't that dedicated right now, and EC2 is not the best cost structure for most Streisand users because of egress pricing. DO is quite good.

**Comment by jimgros** [comment]
Hi,
Thanks for the reply and the feedback. If it helps, I was only using AWS for Streisand. I'm quite novice to cloud computing, so I might have had a few other things that weren't set up properly in the process of trying to install Streisand, but I really don't think I had reached my resource limit on AWS. This might help your development / debugging.
Good luck!
J
