### ISSUE TITLE
China GFW Issues

### ISSUE THREAD

**Issue by mg0314a** [StreisandEffect/streisand#1021]
Was up and working (two lessons: don't use Windows subsystem and use Ubuntu 16.x!) but many issues these last few days with both Shadowsocks and Tor here in China. For example, with Shadowsocks currently this error message:

This site can’t be reached

www.nytimes.com refused to connect.

Also this:

This site can’t be reached

www.google.com unexpectedly closed the connection.

Again to be clear it was working fine but the GFW has been "upping its game". More specifically, I'm using Mode:Global and the likes of bing and baidu are working. But not the banned sites such as gmail, google, etc.

Any suggestions? Streisand Tor implementation not working either (again, was before, for about a week. Sometimes all of the above work "on and off" but then suddenly stop. Similar to Astrill VPN).

### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by z0rc** [comment]
I don't think there is a silver bullet solution to circumvent the GFW. First I'd recommend to read http://blog.zorinaq.com/my-experience-with-the-great-firewall-of-china/. Basically GFW isn't something static, that you can punch holes in it and hope that they will be there tomorrow. It's able to learn and adapt.

Streisand does its best to provide various ways to set you with unrestricted access by providing multiple services. I encourage you try them all. Also it's worth to reprovision streisand instance so it gets a new external IP address or switch to another cloud provider.

**Comment by cpu** [comment]
Firstly, @mg0314a **please fill out the new issue template and include answers to as many of the questions as you can**. I think this is the third time I've asked and I'd appreciate if your next issue could include this information up front. 

Overall, I agree with @z0rc's assessment. 

I also think it might be premature to ascribe these problems to the GFW. It could be a number of more innocuous things at work.

>  More specifically, I'm using Mode:Global

What is "Mode: Global"? 

@mg0314a There isn't a code change/bugfix we can do to address your particular situation but I do appreciate you letting us know about it. It's useful to try and keep pace anecdotally with what's happening in China and Streisand's effectiveness. I'm going to close this issue for now since it isn't immediately actionable.

**Comment by baimafeima** [comment]
@cpu I need some help in selecting a good cloud provider for streisand as I am planning to access it mainly from China. Are there any particular cloud providers that you would recommend for a) working well with streisand in general, b) their privacy advocacy, and c) good speed and accessibility from China? Many thanks for your help.

**Comment by nickolasclarke** [comment]
Your best bet is to test speeds from various hosting providers to determine
which one has the best routing for your particular ISP and location in
China.  Milage varies heavily.  Linode's japan DC, for example, often has
good routing, but it's hard to get a node there.

If your confident enough to deploy on an unsupported provider, just about
anything in Hong Kong will work, as there is usually good peering between
the mainland and HK.

**Comment by cpu** [comment]
@baimafeima I defer to @nickolasclarke here :-) I don't have any experience using the internet from China.

**Comment by baimafeima** [comment]
Thanks @nickolasclarke and @cpu, I will definitely check out Linode.
