### ISSUE TITLE
Easier setup

### ISSUE THREAD

**Issue by baimafeima** [StreisandEffect/streisand#1051]
What are your plans regarding the upcoming feature `Easier Setup`? Would it be possible to make streisand available through a few `snaps`?

**Comment by cpu** [comment]
Hi @baimafeima, 

I think that README item is stale. I don't think the project has any overarching goals in this space that we're working towards. 

@nopdotcom has some WIP for making installing dependencies easier & experimenting with running the Streisand builder from docker.

I'm going to close this issue since it's not related to a code change that can be made on the Streisand repo. If you're interested in follow-up questions please make an issue on the [Streisand discussions repo](https://github.com/StreisandEffect/discussions). Thanks!

**Comment by baimafeima** [comment]
@cpu Thanks for pointing me to the Streisand discussions repo. This looks just like the right place.
