### ISSUE TITLE
Clarify OpenVPN alternate profiles language in docs

### ISSUE THREAD

**Issue by adityarpillai** [StreisandEffect/streisand#1074]
## Expected behavior:
The link states that "Alternate profiles are available if you are on a network that only allows access to ports 80 and 443."

## Actual Behavior:
While there are TCP 443 profiles, there are no TCP 80 profiles.

## Steps to Reproduce:
1. Create the server.
2. Go to OpenVPN.
3. Look at it.

#### Ansible Information

* Ansible version: 2.4.1.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: e03487d9413276e65a971a6acb23f844b7fbd88b
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by cpu** [comment]
Hi @adityarpillai 

Thanks for opening an issue about this. You're correct that Streisand doesn't offer OpenVPN profiles for port 80. That's by design since the Port 443 profiles are intended to be used instead.

I totally agree that the current language: "Alternate profiles are available if you are on a network that only allows access to ports 80 and 443." makes it sound like there should be port 80 profiles. I've retitled & labelled this issue to capture the fact that we should change this language to make it clearer.

**Comment by cpu** [comment]
I've opened #1087 to address clarifying the docs. Thanks!
