### ISSUE TITLE
Which domain do you want to use to host Streisand server?

### ISSUE THREAD

**Issue by NanoG6** [StreisandEffect/streisand#1098]
> Which domain do you want to use to host Streisand server?

This question (or any user input) should be put in the beginning of the installation process, so it can be **unattended installation**.

**Comment by cpu** [comment]
Hi @NanoG6,

Have you tried [following the noninteractive deployment instructions](https://github.com/StreisandEffect/streisand#noninteractive-deployment-advanced)? They allow you to specify an answer to the Let's Encrypt questions in a fully non-interactive manner.

> This question (or any user input) should be put in the beginning of the installation process

This specific question was saved until **after** the genesis roles have run in order to give users a chance to learn the IP address of any newly created cloud instances to use for the required DNS update that needs to be done before the domain can be used for the Streisand instance.

If you can find a way to move this question to the early stage of deployment without making it harder to know the DNS record to update I would be glad to see a PR.

Thanks!

**Comment by nopdotcom** [comment]
Would asking "do you plan to use Let's Encrypt?" in the initial interview help?

**Comment by cpu** [comment]
> Would asking "do you plan to use Let's Encrypt?" in the initial interview help?

Seems like an OK change but in practice conditionally prompting in Ansible is a nightmare. Without a PR its hard to know off-the-cuff if this is viable. If it is I'm all for it :+1:

**Comment by nopdotcom** [comment]
OK, got it. 🛄
