### ISSUE TITLE
Q re. acmetool letsencrypt certificate for hostname.domain.org fails

### ISSUE THREAD

**Issue by wicknet** [StreisandEffect/streisand#1136]
### Expected behavior:
Spun up a new Streisand server on Digital Ocean. Gave it a hostname (hydra). When prompted for domain name for Letsencrypt, gave it my domain name (eg. mydomain123.org).  Also set up an A record separately on my domain's DNS provider, pointing the hostname hydra to the IP of the new server on Digital Ocean.
### Actual Behavior:
During install acmetool reported it was unable to install SSL cert for hydra.mydomain123.org (my actual domain name is different).
### Steps to Reproduce:
1. running acmetool manually with acmetool want hydra.mydomain123.org www.hydra.mydomain123.org reports  errors including acme.storageops: could not obtain authorization and failed all combinations.

2. editing the file at /etc/nginx/sites-available/streisandssl_certificate  shows the following entries, which are accurate and I assume are what acmetool is looking at for getting the cert

/etc/ssl/certs/hydra.mydomain123.org.crt;
  ssl_certificate_key  /etc/ssl/private/hydra.mydomain123.org.key;

Using letsencrypt with hostname.domain.org format as long as a DNS A record exists for that host, works on other virtual hosts on digital ocean (such as wordpress and openVPN/pritunl) so I'm no sure what I'm doing wrong. Any help would be appreciated in installing a proper domain cert instead of the self-signed cert.

Thanks!

[ contents of `streisand-diagnostics.md` here ]

**Comment by cpu** [comment]
Hi @wicknet 

I suspect the attempted validation methods failed for some reason. I can help debug further but only if you share the actual domain name that you used.

Thanks

**Comment by sguberman** [comment]
I am having the same issue. I tried both **hostname.domain.tld** and **domain.tld** at the domain prompt since it wasn't clear to me which way was correct. I have used streisand in the past and this was not an issue for me at the time.

**Comment by cpu** [comment]
@sguberman I can help debug further but only if you share the actual domain name that you used. My email is in my Github profile if you'd prefer to share it privately.

**Comment by sguberman** [comment]
@cpu Thanks, email sent.

**Comment by cpu** [comment]
@sguberman Apologies on the delays. In your case when I tried to verify the server-side Let's Encrypt logs I only saw the ACME client polling an authorization, it never attempted to POST a challenge to begin the validation/issuance process. Very odd!

Since things have gone stale (my fault, apologies again). I recommend you try provisioning a new server from scratch and using the Let's Encrypt integration again. If the problem persists please comment again on this issue and I will investigate anew.

Thanks!

**Comment by ReignOfComputer** [comment]
Am facing the same issue and have sent @cpu more information via email.

> TASK [lets-encrypt : Request initial certificate from Let's Encrypt] ************************************************
> fatal: [52.230.27.32]: FAILED! => {"changed": true, "cmd": ["acmetool", "want", "this.is.replaced"], "delta": "0:00:01.939232", "end": "2018-02-09 03:27:54.762211", "msg": "non-zero return code", "rc": 1, "start": "2018-02-09 03:27:52.822979", "stderr": "20180209032754 [ERROR] acme.storageops: could not obtain authorization for this.is.replaced: failed all combinations\n20180209032754 ...

**Comment by cpu** [comment]
> I only saw the ACME client polling an authorization, it never attempted to POST a challenge to begin the validation/issuance process. Very odd!

@ReignOfComputer Checking the serverside logs I see the same strange behaviour from `acmetool` in your case. On `09/02/2018 02:03:41` the client POSTed the new-authz ACME endpoint and did nothing further. Similarly on `03:27:54`. It was only at `03:59` that a full issuance process was attempted (getting an authz, starting the challenge, calling new-cert, etc). I assume the 3:59 instance was you performing the steps manually since that attempt did result in a certificate being issued.

I'm pretty stumped! I'll try to reproduce this over the weekend. I'm increasingly suspicious that this is a bug in acmetool.
