### ISSUE TITLE
L2TP connection issue

### ISSUE THREAD

**Issue by marvinroger** [StreisandEffect/streisand#1147]
### Expected behavior:

Be able to connect to the VPN via L2TP.

### Actual Behavior:

Unable to connect.

### Steps to Reproduce:

1. Provision an external server with 236eb73bef1748f5fd92589a6c2a70f44612bb31 rev

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*

`vpnpsk"[6] xx.xx.xx.xx #23: ERROR: netlink response for Del SA esp.xxxxxxx@xx.xx.xx.xx included errno 3: No such process`

**Comment by nopdotcom** [comment]
Is Scaleway broken, and if so, should we warn about it?

**Comment by marvinroger** [comment]
Well, everything works except L2TP. Why would not it work? It’s a classic Linux VPS, right?

**Comment by marvinroger** [comment]
The ansible script does execute without any errors.

**Comment by marvinroger** [comment]
Alright, just found that: https://community.online.net/t/switch-kernel/3936

So yeah, seems like Scaleway’s kernel is kind of broken.

**Comment by marvinroger** [comment]
It turns out that there is a way to change the used kernel from within the Scaleway control panel.

<img width="920" alt="capture d ecran 2018-01-13 a 22 46 02" src="https://user-images.githubusercontent.com/990773/34910370-9e8968a2-f8b3-11e7-92c7-7df615eae82d.png">

This kernel in the screenshot, for instance, fixes the issue. I'll let you decide whether or not you want to add this information to a FAQ or something, or if you just want to close this issue.
Just remember that Scaleway offers great VPS, and it's actually the cheapest out of all the providers you support.

**Comment by alimakki** [comment]
@marvinroger Thanks for that little tidbit of information, and the investigation on your part would surely be helpful for others to who wish to deploy on Scaleway.

Out of curiosity, are you deploying on an amd64 or arm architecture?

**Comment by marvinroger** [comment]
Well, thanks for the awesome project.
I’m deploying on an amd64 arch.

**Comment by cpu** [comment]
>  I'll let you decide whether or not you want to add this information to a FAQ or something, or if you just want to close this issue.

I'm going to close this issue. Thanks for mentioning a work around. I'm sure folks that run into Scaleway problems with L2TP will find this issue.

I don't want to add information to a FAQ because Scaleway is unsupported. Their environment has unique challenges and our project is understaffed with the existing providers. I appreciate that some people find the Scaleway service to be the best option for them, unfortunately that will require some more leg-work on the part of the user to chase down these issues. If you want a seamless experience I recommend choosing a supported provider.

Thanks for understanding!
