### ISSUE TITLE
Nginx install failed

### ISSUE THREAD

**Issue by ookangzheng** [StreisandEffect/streisand#1151]
Installed on Ubuntu 16.04 x64 failed
<img width="975" alt="screen shot 2018-01-22 at 7 47 51 pm" src="https://user-images.githubusercontent.com/6301735/35219390-5d3d8e40-ffad-11e7-8641-26db02f29936.png">

**Comment by cpu** [comment]
@ookangzheng "FetchFailedException"  makes me think that there was an issue retrieving the Nginx ppa contents, likely due to something transitory. 

Can you try starting a fresh Streisand provision and seeing if it still fails the same way? If it does, my next suggestion would be to use a supported cloud provider instead of Aruba.it and see if the error persists then as well.

Thanks

**Comment by ookangzheng** [comment]
Hmm... ya it fail again, I changed to Vultr ubuntu 16.04 ... it works..
Thanks

**Comment by cpu** [comment]
@ookangzheng Thanks for following up. I'm going to close this issue since the problem appears to be specific to Aruba.it and it is not a supported platform.

Thanks!
