### ISSUE TITLE
Lets Encrypt role *requires* email address; but copy states it's optional.

### ISSUE THREAD

**Issue by emirpprime** [StreisandEffect/streisand#1170]
### Expected behavior:
When prompted for use of LE, the request for email address says:
```
Which email address do you want to use as contact of Streisand server?

This is an optional question. The email is only used as contact method
of your Let's Encrypt account.

Please type your email below. Press enter to skip.
```

This implies that specifying the email address is not required for LE setup. I would expect LE to continue as the SSL provider.

### Actual Behavior:
Not supplying em email address disables LE and self-signed cert is used instead - ln55 of lets-encrypt.yml requires both to enable `streisand_domain_var != "" and streisand_admin_email_var != ""` and ln63 disables unless both are present `streisand_domain_var == "" or streisand_admin_email_var == ""`

### Steps to Reproduce:
1. Run install, supply domain but no email when prompted with LE questions.

### Resolution:
I would happily create a PR to either:
- refine copy to make it clear that both domain and email are required if LE is desired
- refine when statements to make email optional
but I'm not sure what the intent is. To be honest I don't off the top of my head know if you can request a LE cert without email and haven't tested.

### Ansible Information

* Ansible version: 2.4.2.0
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13.2
* Python interpreter: python
* Python version: 2.7.13

### Streisand Information

* Streisand Git revision: 6c3902ecaf40ac22af0c929e015ea9eb748c86a2
* Streisand Git clone has untracked changes: yes
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by cpu** [comment]
Hi @emirpprime,

Thanks for flagging this issue.

> I would happily create a PR to either:
> 1. refine copy to make it clear that both domain and email are required if LE is desired
> 2. refine when statements to make email optional but I'm not sure what the intent is.

A PR implementing option 2, to allow a blank contact email to continue with Let's Encrypt provisioning is best. Ideally the prompt text/docs can emphasize that providing a contact email, while not mandatory, is highly recommended.

If it turns out to be complicated (for instance because `acmetool`, the ACME client being used under the hood doesn't support no-contact registrations) then option 1 would be better than a big complicated diff :-)

> To be honest I don't off the top of my head know if you can request a LE cert without email and haven't tested.

I can confirm that Let's Encrypt allows you to create an ACME account without specifying a contact email. This is by design. The recommendation is to provide one (for both getting expiration warnings and to hear about subscriber agreement updates, critical security issues, etc) but the service respects the wishes of users that choose not to provide an email anyway. Certbot goes as far as to call the "no-email" registration flag `--register-unsafely-without-email` to highlight that its a strong recommendation to provide one.

Thanks for offering to write a PR - Please let us know if you get stuck and need some pointers/advice!

**Comment by emirpprime** [comment]
@cpu First run: #1177 

Tested against DO which was successful - I don't imagine it would vary with other platforms but I'm not in a position to try. *Seems* like just supplying blank to acmetool's response-file is accepted fine.

Let me know if you think the wording is off still.

**Comment by cpu** [comment]
@emirpprime Thank you! I did a test run both with/without LE enabled on a different cloud provider and was satisfied that everything worked as expected :ok_hand: 

I'm going to close this issue since 1177 is merged now. Thanks again for your contribution! :tada:
