### ISSUE TITLE
gateway mode and ports

### ISSUE THREAD

**Issue by zenny** [StreisandEffect/streisand#1206]
Hi,

1. Can anyone explain how to use the Streisand serve as a gateway to other VPNs, particularly with wireguard/OpenVPN/IPSEC?

2. What are the ports that one needs to open in the firewall/gateway to avail all Streisand services?

Cheers,

**Comment by cpu** [comment]
Hi @zenny, thanks for opening an issue.

> Can anyone explain how to use the Streisand serve as a gateway to other VPNs, particularly with wireguard/OpenVPN/IPSEC?

I'm not sure I understand. You want your Streisand server to route traffic from VPN clients over a VPN connection to another server? This isn't something we can support. You're welcome to open an issue in the [discussions repo](https://github.com/StreisandEffect/discussionshttps://github.com/StreisandEffect/discussions) but this is well outside what Streisand intends to do :-) If anonymity is your goal I recommend Tor instead of trying to shoehorn another hop into a VPN based solution.

> What are the ports that one needs to open in the firewall/gateway to avail all Streisand services?

If you use a first-class provisioning mode (DigitalOcean, AWS, Linoide, GCE, etc) then Streisand opens the required ports for you. If you use an advanced provisioning mode and need to do additional firewall work the required ports are in `generated-docs/` next to the initial gateway configuration info in a fill called `<instance name>-firewall-information.html`.

Hope that helps!

**Comment by zenny** [comment]
Another VPN hop is needed when one needs to use bandwidth-hungry apps which Torproject discourages to use.

Thanks for the pointer about the ports.
