### ISSUE TITLE
Existing server setup su password

### ISSUE THREAD

**Issue by Lexy2** [StreisandEffect/streisand#1294]
### Expected behavior:
Ansible should ask for become password once and use it for all elevated actions on the server.

### Actual Behavior:
Installation fails because of unknown become password.

### Steps to Reproduce:
1. Set up an existing server. 
2. Set up a sudo password but certificate authentication for SSH logon.
3. Run server provisioning.
4. Installation fails because of unknown sudo password.

[ contents of `streisand-diagnostics.md` here ]

##### *Target Cloud Provider:*
custom
##### *Operating System of target host:*
Ubuntu 16.04
##### *Operating System of client:*
Linux Mint 18.3
##### *Version of Ansible, using `ansible --version` :*
ansible 2.5.1
  config file = /home/lexy/streisand/ansible.cfg
  configured module search path = [u'/home/lexy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.1-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
0ab3ab9248e3903205e8d2f04527af3defb57778

**Comment by cpu** [comment]
> Target Cloud Provider:
> custom

You are expected to use SSH key authentication for existing/localhost provisioning. 

If you are being prompted for a password by Streisand for connecting to the instance over SSH or to elevate to root it is because of the configuration of your server.

Please use a supported provider (DigitalOcean, Linode, AWS, etc). The advanced modes presume that you are able to debug your own problems and we unfortunately can't offer much support, specifically for issues like these that are outside of the jurisdiction of Streisand.

Thanks!

**Comment by Lexy2** [comment]
Of course I am able to debug my own problems! The thing is, Streisand does not even have an option to input a become password, and that should be there.

**Comment by cpu** [comment]
> Why wouldn't you be able to support it? It's just flip of a switch in Ansible config?

I didn't realize there was a config switch we could use. Are you interested in submitting a PR that I can evaluate? If it's just a config switch without any adverse side effects for normal usage I'd be OK with supporting it.

**Comment by Lexy2** [comment]
Certainly, thank you for your prompt response, I'll work on PR for the issue.

**Comment by cpu** [comment]
@Lexy2 Excellent! Thank you very much!
