### ISSUE TITLE
SSH: Should not allow root logins to existing servers if they were disallowed previously

### ISSUE THREAD

**Issue by Lexy2** [StreisandEffect/streisand#1320]
### Expected behavior:
When provisioning a server, it might be preconfigured to disallow root logins. After setting up Streisand, sshd config should keep it the same way.

### Actual Behavior:
Streisand enables root logins unconditionally.

### Steps to Reproduce:
1. Configure `/etc/ssh/sshd_config` on an existing server with `PermitRootLogin No`
2. Run server provisioning with `ANSIBLE_SSH_USER=user ./streisand`
3. Wait until SSH role is applied.
4. Observe the changes to sshd_config on the server.

[ contents of `streisand-diagnostics.md` here ]

##### *Target Cloud Provider:*
custom
##### *Operating System of target host:*
Ubuntu 16.04

##### *Operating System of client:*
Ubuntu 16.04

##### *Version of Ansible, using `ansible --version` :*
ansible 2.5.1
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
42c7ba73a9c92c1d73cc970c7c9e403d78b983c9

**Comment by cpu** [comment]
Hi @Lexy2 

This is by-design. That's why the warning text for the existing servers says that existing configuration may be overwritten:
https://github.com/StreisandEffect/streisand/blob/42c7ba73a9c92c1d73cc970c7c9e403d78b983c9/streisand#L147-L149

> When provisioning a server, it might be preconfigured to disallow root logins. After setting up Streisand, sshd config should keep it the same way.

It's too difficult to write Streisand such that it can take into account existing configuration and merge its own changes as required.

I'm going to close this issue for now since I think addressing this specific instance will set the expectation that Streisand should be merging its required changes into existing configuration files beyond the SSHD and it's too much work that is too outside the scope of the project.

Thanks!

**Comment by cpu** [comment]
> Thanks, @cpu . I still think that opening SSH root login is an undesirable configuration for a secure server. I would rather let Streisand connect as a regular user and become root remotely.

That's fair feedback but as a note, Streisand's SSHD config does allow root login but the only supported authentication mode is `PublicKey` and password authentication is disabled. This seems like a reasonable configuration for a secure server. 

I do notice we're setting `PermitRootLogin: Yes` : https://github.com/StreisandEffect/streisand/blob/42c7ba73a9c92c1d73cc970c7c9e403d78b983c9/playbooks/roles/ssh/files/sshd_config#L28

It would be slightly better if we set `PermitRootLogin without-password` so that someone that further customizes the configuration doesn't accidentally introduce password based root logins. That seems like a good follow-up to this issue if you're interested :-)

**Comment by Lexy2** [comment]
I would agree to this compromise. `PermitRootLogin without-password` looks better.

Thank you!
