### ISSUE TITLE
Users connected to same VPN profile get disconnected

### ISSUE THREAD

**Issue by dandaka** [StreisandEffect/streisand#1337]
### Expected behavior:

1) Any user can use any openvpn profile
2) Many users can work via one profile
3) If 2) isn't possible, there should be a way to resolve conflicts

Documentation says:

> The server you will be connecting to has been configured to allow clients to share the same certificate and private key, but you may still wish to give your phone and laptop different keys, for example.

### Actual Behavior:

When few users try to use same profile (MacOS, Tunnerblick), VPN server kicks first one and connects next one. Second user reconnect and kicks the first one. This goes on and on.

### Steps to Reproduce:
1. Install latest Streisand
2. Install Tunnelblick for 2 machines
3. Download same OpenVPN profile
4. Connect simultaneously to this single profile
5. It doesn't work, one user gets kicked after another

Log https://gist.github.com/dandaka/4aaa494861de0867d426924c5c43d873

**Comment by alimakki** [comment]
@dandaka, this is the expected behavior for OpenVPN as of PR #1005, and is consistent with the behavior of WireGuard and OpenConnect insofar as allowing only 1 client per given credential. If your use case requires it, you can easily commenting out the relevant section in the generated OpenVPN configuration.

**Comment by dandaka** [comment]
Maybe documentation should include that information, instead of stating opposite?
