### ISSUE TITLE
There is no generated docs for using Tinyproxy?

### ISSUE THREAD

**Issue by NightMachinary** [StreisandEffect/streisand#1354]
![image](https://user-images.githubusercontent.com/36224762/40515929-11426354-5fc4-11e8-81f4-02c8a31a0e87.png)

What exactly does Tinyproxy do?

### Ansible Information

* Ansible version: 2.5.3
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13.3
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: 4c791b045c14725075e76dd766b8e576db311707
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

**Comment by cpu** [comment]
> There is no generated docs for using Tinyproxy?

The TinyProxy documentation is available under the "SSH" link in "Connection Instructions". 

> What exactly does Tinyproxy do?

The [Tinyproxy website](https://tinyproxy.github.io/) says: 

> Tinyproxy is a light-weight HTTP/HTTPS proxy daemon for POSIX operating systems. Designed from the ground up to be fast and yet small, it is an ideal solution for use cases such as embedded deployments where a full featured HTTP proxy is required, but the system resources for a larger proxy are unavailable.

In the context of Streisand it is useful for forwarding multiple ports from through a SSH tunnel and maintaining that forwarded connectivity across network changes.

I'm going to close this issue now since the question has been addressed. Thanks,
