### ISSUE TITLE
could you please translate into chinese (DOCS)

### ISSUE THREAD

**Issue by Blucezhang** [StreisandEffect/streisand#1355]
### Steps to Reproduce:
1. 

[ contents of `streisand-diagnostics.md` here ]

**Comment by cpu** [comment]
Hi @Blucezhang,

We would certainly welcome a full translation of our documentation into Chinese. We do not have any maintainers who are able to provide this translation ourselves. There is an open issue for such a translation: https://github.com/StreisandEffect/streisand/issues/862 

Native speakers who want to help should [check our localization documentation](https://github.com/StreisandEffect/streisand/blob/master/documentation/localization_howto.md). We have an [open issue to improve translation tooling](https://github.com/StreisandEffect/streisand/issues/1234).

Thanks for the request. Since #862 already exists I'm going to close this issue to consolidate discussion.

**Comment by Blucezhang** [comment]
@cpu thinks a lot
