### ISSUE TITLE
OpenConnect breaks the route table when using the use proxy

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1357]
when I run OpenConnect with the proxy option enabled after a few minutes, I completely break down the Internet and get lost.

Then through ping 127.0.0.1 does not work and only a complete reboot of the system restores the routing table
is this normal behavior? Who can help me how to be why this happens?

The task I had was such that I would use
OpenConnect + shadowsocks
and in OpenConnect I wanted to set the option to use a proxy

But this bundle does not work as I wrote above the problem

**Comment by rdbox** [comment]
what information should be provided?

**Comment by cpu** [comment]
@rdbox Answers to all of the following:

### Expected behavior:

### Actual Behavior:

### Steps to Reproduce:
1. 

If you have a `streisand-diagnostics.md` file in your Streisand directory please
paste its contents below. 

[ contents of `streisand-diagnostics.md` here ]

If you *do not* have a `streisand-diagnostics.md` file to share, please answer 
the following questions below manually

### Additional Details:
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

**Comment by rdbox** [comment]
I do not have this program

```
root@streisand-sgr:~# ansible --version
The program 'ansible' is currently not installed. You can install it by typing:
apt install ansible
root@streisand-sgr:~#
```

**Comment by cpu** [comment]
> root@streisand-sgr:~#

Similar to your other issue it looks like you're trying to collect this information from the Streisand server **not** the place that you created the Streisand server from by running `./streisand`. Somewhere there must be an Ansible installation that was used to create this instance.

**Comment by rdbox** [comment]
Yes you are right, I deleted the second drop from where was the installation of streisand.

what now do I have to collect information for you?

**Comment by rdbox** [comment]
the first time I see such a collection of data to identify the product.
I thought that it would be enough just to have a log file or show a version.
But I did not find in your description that it was necessary to save the server with this was setup.

I needed to remove the old server from where I put streisand
because it took away money from me for the simplicity of this server. And I had to remove it

**Comment by cpu** [comment]
> Yes you are right, I deleted the second drop from where was the installation of streisand.
> what now do I have to collect information for you?

Ahh, I understand. That makes this tricky since that information isn't stored on the Streisand server. That's something we should probably consider fixing for the future.

Let's try our best without that information in this case.

>  when I run OpenConnect with the proxy option enabled after a few minutes, I completely break down the Internet and get lost.Then through ping 127.0.0.1 does not work and only a complete reboot of the system restores the routing table

Can you answer a few more questions?

1) When you say that "a complete reboot of the system restores the routing table", does this mean a complete reboot of the Streisand server, or of the computer you're connecting to the Streisand server from?

2) What operating system/version are you using on the machine you're connecting to the Streisand server from?

3) What OpenConnect version are you running on the machine you're connecting to the Streisand server from?
--

**Comment by rdbox** [comment]
**1. Yes you are right again, I need to restart my client computer. from which I am connected.**
**2. I use windows 7 on the client machine**
**3. version 1.5.3 32 bit**

I downloaded this version at https: //ip_server/mirror/openconnect/
Windows
openconnect-gui-1.5.3-win32.exe
Checksum: sha256:b1d4bd76b41f32d08287bf043b3dc8c798a145c02319217d45a74b0d9545a23d
macOS

**Comment by rdbox** [comment]
such behavior when the route breaks occurs suddenly or after 20-30 minutes.
I can not understand why this is happening.

**Comment by cpu** [comment]
@rdbox Thanks for the information. I suspect the problem is either a bug with OpenConnect or the result of your upstream network filtering/blocking the OpenConnect connection.

We might be able to glean more information by checking the Streisand server's `ocserv` logs. I can provide some guidance on that later I have to leave for work now.

**Comment by rdbox** [comment]
I need to send a log file here?

**Comment by alimakki** [comment]
@rdbox I think the OpenConnect mailing list is where you question might be best answered: https://www.infradead.org/openconnect/mail.html
