### ISSUE TITLE
Could not install packages due to an EnvironmentError: [Errno 36] Help

### ISSUE THREAD

**Issue by orbisunom** [StreisandEffect/streisand#1414]
Hello i try to install streisand auto installer on my linux mint but i get this error

Found existing installation: wheel 0.31.1
    Uninstalling wheel-0.31.1:
      Successfully uninstalled wheel-0.31.1
Could not install packages due to an EnvironmentError: [Errno 36] File name too long: '/home/john/streisand/venv/lib/python2.7/site-packages/libcloud/test/compute/fixtures/azure_arm/_subscriptions_99999999_9999_9999_9999_999999999999_resourceGroups_000000_providers_Microsoft_Compute_virtualMachines_test_node_1_InstanceView.json'

**Comment by alimakki** [comment]
@orbisunom, before we get started, can you please fill out the issue template?



### Expected behavior:

### Actual Behavior:

### Steps to Reproduce:
1. 



[ contents of `streisand-diagnostics.md` here ]


### Additional Details:
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

**Comment by orbisunom** [comment]
Hi alimakki I already resolve ,, I create a user with ecnryptd home ,, now I just create a new user and it's work ,, thank you for your time
