### ISSUE TITLE
Stops at wireguard role

### ISSUE THREAD

**Issue by gelato** [StreisandEffect/streisand#1428]
'wireguard_server_public_key_file' is undefined when streisand gets to wireguard role.
Provisioning on existing server. Everything enabled.

**Comment by alimakki** [comment]
Hi @gelato 

Have you tried re-running the script?

If you could also share some of the details in the issue template it would be helpful:



[ contents of `streisand-diagnostics.md` here ]


### Additional Details:
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

Thanks

**Comment by gelato** [comment]
The error i noted before is reproduced only on the first run of this script, on second and every other runs i get:
FAILED! => {"changed": false, "msg": "Could not find the requested service stunnel4.service: host"}



### Ansible Information

* Ansible version: 2.6.2
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 1d8ee35e16f350737a783c967c669ba462d6334f
* Streisand Git clone has untracked changes: yes
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 10

Target Cloud Provider: amazon
Operating System of target host: ubuntu linux 16.04
Operating System of client: ubuntu linux 16.04
Version of Ansible, using ansible --version : 
ansible 2.6.2
  config file = /home/belcros/dev/streisand/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

Output from git rev-parse HEAD in your Streisand directory : 1d8ee35e16f350737a783c967c669ba462d6334f

**Comment by gelato** [comment]
And after i added ignore_errors: yes to that part of stunnel4 role, which prevented from proceeding:

TASK [wireguard : Generate private and public key for the server] *************************************************************************
fatal: [aws-1.skynerv.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'wireguard_server_public_key_file' is undefined\n\nThe error appears to have been in '/home/belcros/dev/streisand/playbooks/roles/wireguard/tasks/main.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Generate private and public key for the server\n  ^ here\n"}

**Comment by alimakki** [comment]
@gelato 

The stunnel failure in your second attempt is definitely a bug. I will try and reproduce your error.

Just so that I understand how you're trying to set up this environment: did you spin a VM on AWS first and run streisand on an existing server?

**Comment by gelato** [comment]
Yes, i firstly set up aws vm, then launched streisand in existing server mode.

**Comment by alimakki** [comment]
I attempted to reproduce your issue however I was not able to.

It would be worth trying again on a fresh VM, and running the script on it using "localhost (option 7)" rather than existing server.

That being said when provisioning to Amazon, it's best to run the script from your local machine and choose Amazon from the list of supported providers.

If your client machine happens to be a Windows 10 device, you could very well use Windows Subsystem for Linux and downloading Ubuntu from the store, and following the README instructions based off of Ubuntu.

**Comment by cpu** [comment]
> The stunnel failure in your second attempt is definitely a bug. I will try and reproduce your error.

I believe this was fixed in https://github.com/StreisandEffect/streisand/commit/56ce35b85002ee1a30b0877c0dc358808ddf1709

> Yes, i firstly set up aws vm, then launched streisand in existing server mode.

@gelato I don't recommend using Streisand this way. Existing server mode is an advanced feature and we do not have the time to do much support for it. Worse, running Streisand in this manner will not apply firewall rules to the AWS instance that Streisand usually handles when you let it create the AWS instance for you.

I recommend you try using a better supported provisioning mode. I'm going to close this issue for now. Thanks!
