### ISSUE TITLE
no generated-docs

### ISSUE THREAD

**Issue by rvitguy** [StreisandEffect/streisand#1437]
### Steps to Reproduce:
1. installed Streisand per instructions
2. looked for generated-docs folder in same location as repo was cloned

[ contents of `streisand-diagnostics.md` here ]

##### *Version of Ansible, using `ansible --version` : 
config file = /home/clone/streisand/ansible.cfg
  configured module search path = [u'/home/rgitguy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/clone/streisand/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/clone/streisand/venv/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

**Comment by nopdotcom** [comment]
Interesting. So there's nothing in `/home/clone/streisand/generated-docs`?

Could you try using the virtualenv? `./util/venv-dependencies.sh ./venv`

**Comment by admzzz** [comment]
had to confirm: no generated docs after installing streisand on amazon aws with ubuntu server 16.04 locally

**Comment by cpu** [comment]
I'm going to close this issue since the original poster hasn't replied with results from trying the venv approach to installing Streisand to do a deploy.

> had to confirm: no generated docs after installing streisand on amazon aws with ubuntu server 16.04 locally.

@admzzz I don't recommend running Streisand on existing AWS servers. This will miss critical firewall policy changes Streisand does on your behalf when creating an AWS instance. It is better to let Streisand create the instance for you.
