### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by neeks77** [StreisandEffect/streisand#1449]
Hi All,

I had issues during the install with errors like this: "[WARNING]: Found both group and host with same name: localhost"

TASK [genesis-linode : Create the server] **************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "linode-python required for this module"}
	to retry, use: --limit @/Users/nikolaypetukhoff/streisand/playbooks/linode.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   

Any ideas?

**Comment by alimakki** [comment]
Hi @neeks77,

Did you follow the setup instructions on the README? the Linode dependencies should have been installed by using the venv script:

```
 ./util/venv-dependencies.sh ./venv
```

followed by

```
source ./venv/bin/activate
``

**Comment by patthiel** [comment]
Hi @neeks77 , I investigated this issue and determined that Personal Access Tokens created via https://cloud.linode.com are not working as expected with the Streisand setup script. Instead of using the new manager, you can generate your token here: https://manager.linode.com/profile/api_key_create

Insert that token into the Streisand setup as instructed and it should work. I will personally investigate why the personal access tokens generated in cloud.linode.com are not working as expected here and follow up. Until then, I hope this helps you and others that may come across this issue.

**Comment by cpu** [comment]
Hi @neeks77 - since @alimakki's questions went unanswered and @patthiel has identified the most likely cause of your problems I'm going to close this issue. Thanks for bringing this to our attention!

@patthiel Thanks for digging into the issue. I remember seeing this when the V3 API was in beta and forgot to file an issue to follow up :sweat: I've opened a new issue to track this problem specifically: https://github.com/StreisandEffect/streisand/issues/1467 If you're interested I'd love for help filling in details about the required linode ansible module change (and a PR to use it when its available!)
