### ISSUE TITLE
Migrate to Linode API v4

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#1467]
(Originally articulated in https://github.com/StreisandEffect/streisand/issues/1449 by @patthiel. Thanks!)

### Expected behavior:

Streisand can create a Linode instance using the modern V4 API token created via the https://cloud.linode.com  interface.

### Actual Behavior:

Streisand can only create Linode instances using a deprecated V3 API with API tokens created from a legacy location: https://manager.linode.com/profile/api_key_create

### Steps to Reproduce:
1. Create a V3 API token
1. Follow the Streisand setup for Linode and provide the V3 API token

### Fix

Streisand should migrate to the V4 API, or remove Linode support since it will break when the V3 API is removed. It sounds like switching to V4 would be blocked on an updated ansible linode module.

**Comment by patthiel** [comment]
The issue highlighted here is correct, but the referenced api versions are incorrect. Streisand is currently compatible with the deprecated Linode APIv3. Streisand should migrate to using the Linode APIv4. Switching to using V4 is blocked the ansible linode module

**Comment by cpu** [comment]
@patthiel Oops! Thanks, fixed to reflect we're using V3 now and need to switch to V4.

**Comment by e-ht** [comment]
Is anyone working on this currently? I am familiar with the Linode API and could take this on.

**Comment by alimakki** [comment]
@e-ht PRs are always welcome :)

**Comment by patthiel** [comment]
@e-ht there is a Linode API v4 ansible module that was developed over the last few [months](https://github.com/ansible/ansible/pull/46151). It is due to ship in Ansible 2.8 in May 2019, according to this roadmap: https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_8.html

You may want to hold off until then, as the module will make this task considerably easier. I am also happy to help review and/or implement this work once the Ansible 2.8 is out.

**Comment by patthiel** [comment]
Looks like i neglected to update this ticket a while back! https://github.com/StreisandEffect/streisand/pull/1580 implements this issue, it can be closed now ❤️

**Comment by nopdotcom** [comment]
OK!
