### ISSUE TITLE
RSA Fingerprint Doesn't Match

### ISSUE THREAD

**Issue by Ev3y** [StreisandEffect/streisand#462]
When I connect to my server the fingerprint displays in hexadecimal instead of base64, so I connect to the server without adding the key to the cache, and run the command `ssh-keygen -lf ~/.ssh/id_rsa.pub`. However, when I do so, the fingerprint shown does **not** match that listed in the generated instructions on my server; furthermore, the text after the fingerprint is "streisand (RSA)" instead of the "root@[servername] (RSA)" shown in the generated instructions on my server. Considering that I'm connecting with a randomly-generated username instead of root, are you sure the fingerprint should say  "root@[servername] (RSA)"?

Anyway, I followed the instructions exactly, so you should consider updating them considering the fingerprint PuTTY provides is in a different format from the one in the generated instructions on the Streisand server.

Am I doing this wrong somehow? Or am I doing this right and should I be worried that the fingerprint doesn't match? Could this have something to do with me deleting the SSH key from my DigitalOcean account after closing the droplet I used to spin up the Streisand droplet?

**Comment by cpu** [comment]
Hi @Ev3y - This issue is quite stale - apologies that nobody ever got back to you. We've made some improvements in issue triage since 2016 that will hopefully prevent these things from slipping through the cracks in the future.

Since there has been significant work done on Streisand since Dec 2016 I'm going to close this issue for now. If you're interested in following up further I recommend you try to provision a new instance using the current code in master. If the fingerprint still does not match expected after following the generated instructions then opening a new issue that completes the pre-populated issue template questions is the best way to continue.

Thanks!
