### ISSUE TITLE
Streisand wrapper python version detection incompatible with FreeBSD

### ISSUE THREAD

**Issue by cpu** [StreisandEffect/streisand#640]
@chipitsine reports that https://github.com/jlund/streisand/commit/57f8e0f828dfb6322a695b46ec7b5620e0c98575 breaks on FreeBSD:
>  this breaks FreeBSD, because there's no "python" on FreeBSD executable is either "python2" or "python3xx"

**Comment by bartekrutkowski** [comment]
@cpu @chipitsine that's not exactly correct - on FreeBSD there is a meta port (and meta package as well) `python` that will install Python 2.7 (for now) and it will take care of aliasing python to python2, so when Python 3.x is being installed, they can coexist since `python` and `python2` will invoke `python2` and `python3` will invoke `python3` as expected.

**Comment by cpu** [comment]
@bartekrutkowski Thanks for clarifying!!

Since it sounds like this is a non-issue and nobody other than @chipitsine has complained so far I'm in favour of closing this issue until there's more evidence that there is a problem.
