### ISSUE TITLE
Create CONTRIBUTING.md and/or TODO.md 

### ISSUE THREAD

**Issue by nickolasclarke** [StreisandEffect/streisand#699]
We've got a quite a few new features and changes that we'd like to see. In order to maximize our ability to leverage our community to accomplish these, we need to do the following:

- [ ] Create a contributing guide with general guidelines on how to contribute to the project. 
- [ ] create a prioritized TODO list that includes at least a "Beginner friendly" classification. Possibly also break down by type: such as new service provider, new service, architectural changes, etc.

**Comment by chipitsine** [comment]
I suggest to focus on PR and ISSUE templates first

https://github.com/blog/2111-issue-and-pull-request-templates

that's what people read when they try to contribute.

**Comment by cpu** [comment]
@chipitsine Some of that has started in https://github.com/jlund/streisand/pull/688, there is a related issue as well: https://github.com/jlund/streisand/issues/656

**Comment by cpu** [comment]
We have a PR and Issue template, as well as a CONTRIBUTING.md.

I suspect all of the above could use some tune-ups but this issue is pretty stale. I'm going to close it for now and suggest that if folks think there are improvements to be made that they open new issues with concrete recommendations (and hopefully accompanying PRs!).

Thanks!
