### ISSUE TITLE
Local Server

### ISSUE THREAD

**Issue by manue1988** [StreisandEffect/streisand#72]
Hi I'm trying to install streisand in a clean Debian 7 distribution, but I've got the following error:
fatal: [192.168.31.210] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh
Fatal: no hosts matched or all hosts have already failed -- aborting

What can I do to solve these issues?

Thank you

**Comment by skaurus** [comment]
I edited files as manuel-delverme suggested (too bad this isn't covered in README), but after that nginx, for example, is configured to listen on 127.0.0.1 and useless, of course. I could only guess that rest of the services may be broken too.
By the way, nginx restart failed because 443 port was taken by sslh.

I tried changing [streisand-host] to external IP of my box and had rerun script, it run without errors, but nginx config stayed the same.
What should I do now?
Debian 7 latest, kernel 3.16 from backports, python 2.7.3.

Maybe streisand script should have an option "install on a localhost"? Seems like a common situation for configuring your personal proxy/vpn/etc server.

Sorry if I'm asking something stupid or/and in the wrong place.

**Comment by skaurus** [comment]
Also I had to run `ansible-playbook playbooks/streisand.yml` with `sudo`, because otherwise I had an error:

    failed: [127.0.0.1] => (item=curl,gnupg,markdown,ntp,python-software-properties,wamerican-huge) => {"failed": true, "item": "curl,gnupg,markdown,ntp,python-software-properties,wamerican-huge"}
    stderr: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
    E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

    msg: 'apt-get install 'markdown' 'ntp' 'python-software-properties' 'wamerican-huge'' failed: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
    E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

    FATAL: all hosts have already failed -- aborting

and nginx permissions is messed up. I had to change them on `/etc/nginx/htpasswd` for example, to get nginx working at all.

Also certificate for nginx was generated for 127.0.0.1 and not my public ip.
