### ISSUE TITLE
openconnect GPG key not importing behind firewall

### ISSUE THREAD

**Issue by nikksno** [StreisandEffect/streisand#960]
I'm behind a restrictive firewall. I'm provisioning a local server [192.168.xxx.yyy] from the same local network.

### Expected behavior:

GPG key gets imported at step `TASK [download-and-verify : Nikos Mavrogiannopoulos signs the OpenConnect downloads. Import the correct GPG key.]`

### Actual Behavior:

The client gets stuck at:

TASK [download-and-verify : Nikos Mavrogiannopoulos signs the OpenConnect downloads. Import the correct GPG key.] *****************************
FAILED - RETRYING: Nikos Mavrogiannopoulos signs the OpenConnect downloads. Import the correct GPG key. (10 retries left).
FAILED - RETRYING: Nikos Mavrogiannopoulos signs the OpenConnect downloads. Import the correct GPG key. (9 retries left).
FAILED - RETRYING: Nikos Mavrogiannopoulos signs the OpenConnect downloads. Import the correct GPG key. (8 retries left).

[...]

### Steps to Reproduce:

Provision a local server from inside its local network, which is behind a restrictive firewall.

[ contents of `streisand-diagnostics.md` here ]

#### Ansible Information

* Ansible version: 2.3.1.0
* Ansible system: Unknown
* Host OS: Unknown
* Host OS version: Unknown
* Python interpreter: python
* Python version: Unknown

#### Streisand Information

* Streisand Git revision: 40b3b1a695ddc77055203784b297378b6f9e73c0
* Streisand Git clone has untracked changes: yes
* Genesis role: None

#### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

### Proposed solution:

Change the port on which the gpg keyserver is contacted?

To do a rought and tough test, I modified the code inside:

`streisand/playbooks/roles/download-and-verify/tasks/main.yml`

on line 3 column 56 changing:

`{{ gpg_key_server_address }}` to `{{ gpg_key_server_address }}:80`

and it worked.

I still have to test this on a brand new client, I'll report back if I know something new.

Thanks!

**Comment by nikksno** [comment]
Update: here too:

`playbooks/roles/tor-bridge/tasks/mirror-common.yml`

**Comment by cpu** [comment]
@nikksno To clarify: Your local network environment doesn't allow any outbound traffic on 443?

I don't think your proposed change is the best for all users but maybe there's a compromise that would make it easier for you to adjust this as required?

**Comment by nikksno** [comment]
It does allow both 80 and 443, but reading [this](https://serverfault.com/questions/168826/how-to-install-gpg-keys-from-behind-a-firewall) I was under the impression that the default port for the gpg key import command was 11371.

How is the retrieval process secured? Would using port 80 be detrimental to security?

I can confirm anyway that it does work changing to port 80 in those two instances. I know that's not the clean way to make the change, that was just a quick and dirty test.

Thanks!

**Comment by cpu** [comment]
> It does allow both 80 and 443, but reading this I was under the impression that the default port for the gpg key import command was 11371.

@nikksno You're right. I'm not sure why my brain immediately jumped to 443. Thanks for pointing out that HKP defaults to 11371.

> How is the retrieval process secured? Would using port 80 be detrimental to security?

From the perspective of the integrity of the received key it wouldn't be detrimental to use port 80. The key is signed and we [verify the fingerprint of the key received matches the full fingerprint expected](https://github.com/jlund/streisand/blob/c58d33776cf19570486858d636aad1d8c1c09d2f/playbooks/roles/download-and-verify/tasks/main.yml#L16).

It also looks like we're using `x-hkp://pool.sks-keyservers.net` globally. HKP is HTTP without TLS so using port 80 over 11371 doesn't change anything meaningful.

Thinking about this more however I think the best course of action is to switch to to using `hkps.pool.sks-keyservers.net`. This will use HKP over HTTPS which is better for privacy. According to [the sks-keyservers pool overview](https://sks-keyservers.net/overview-of-pools.php) this domain listens on port 443:

>  This is a pool containing only servers available using hkps. Regular A and AAAA and SRV records are included for port 443 servers, and a lookup is performed for _pgpkey-https._tcp on the individual servers to determine if a hkps enabled service is listening on another port. At this point, however, servers not running on port 443 are not included.

Since 443 is also open on your network would this solve your problem as well?

**Comment by nikksno** [comment]
This is absolutely the best solution, independently of my requirements, so I would upvote it immediately in any event. Additionally, it also works for my situation, as 443 and 80 are the two open ports on my workplace's network [who uses proxies any more? ;] so even better. Thanks so much!

**Comment by nikksno** [comment]
Also FYI I noticed that many environments that use a filtered DNS service like openDNS family shield [like my school does] poison the torproject.org zone, so that step often fails in my experience. Outbound requests on port 53 are also blocked usually when this is the case so performing a lookup directly on, say, 8.8.8.8 would not be a solution. Do you think it would have any value to look into maintaining a list of genuine IPs of their servers and coding them inside Streisand as a fallback in case of failure to contact their servers? I've had to set torproject.org, deb.torproject.org, and dist.torproject.org in /etc/hosts on the server prior to running the provisioning from the client to make it work. I've had this issue several times. Let me know what you think.

**Comment by cpu** [comment]
> This is absolutely the best solution, independently of my requirements, so I would upvote it immediately in any event. Additionally, it also works for my situation, as 443 and 80 are the two open ports on my workplace's network [who uses proxies any more? ;] so even better. Thanks so much!

Great. I've opened https://github.com/jlund/streisand/issues/963 with some implementation notes. I'm going to close this issue for now since there isn't outstanding work that should be tracked separately from 963.

> Also FYI I noticed that many environments that use a filtered DNS service like openDNS family shield [like my school does] poison the torproject.org zone, so that step often fails in my experience.

Generally Streisand is meant to be provisioned on a server in a clean network that clients in filtered networks will connect to. Are you creating the Streisand instance on a server that is itself on the filtered network? The computer running the `./streisand` script shouldn't need to do DNS lookups for `torproject.org`, just the server being provisioned.

> Do you think it would have any value to look into maintaining a list of genuine IPs of their servers and coding them inside Streisand as a fallback in case of failure to contact their servers?

This sounds really brittle. Why not create a Streisand instance in a datacenter that doesn't have this sort of filtering?

**Comment by nikksno** [comment]
@cpu sorry for the very late reply. I do usually deploy streisand in datacenters, but also deploy it on internet-facing local network servers to set up VPN connections to that local network from outside. When such private networks are filtered the above mentioned steps fail, but I understand that since streisand is not meant to be provisioned on local networks avoiding this kind of private network DNS filtering is not your goal. I am still having the same issues with GPG keys, but I see issue #963 is still open, so all good for now. Thanks for your help.
