### ISSUE TITLE
Unable to start service nginx: Failed to start nginx.service: Unit nginx.service is masked

### ISSUE THREAD

**Issue by mg0314a** [StreisandEffect/streisand#991]
Hi there. First of all THANK YOU for this project. I am based in China and this is really meaningful to me. Secondly, some questions and an error message.  Full disclosure: I am running my local shell using Bash on Ubuntu on Windows. Also I am running Streisand against an existing linode. I had another error message but I was able to solve by changing the boot setting to GRUB.
  I am currently receiving this error message: RUNNING HANDLER [tor-bridge : Restart Nginx for the Tor hidden service vhost] ***************************************
fatal: [this is my remote server IP]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service nginx: Failed to start nginx.service: Unit nginx.service is masked.\n"}
Any suggestions?
  Next, some questions. If I receive an error message, does that mean that I need to rerun the streisand script from the beginning? or is it partially installed? I saw from ps -A that services were running but it wasn't obvious to me that I was up and running, mostly because I wasn't able to find the documentation file(s).
  On a related note, I am currently rerunning the script only this time without selecting Tor. Is there a way to install just Tor later?
  Finally an FYI, running Streisand script takes several hours for me. Not sure if that's related to my Internet connectivity or what, but wanted to bring it to your attention.

THANK YOU again. I owe your team a beer if you are ever in Beijing.

Cheers!

**Comment by cpu** [comment]
Hi again @mg0314a 

> Hi there. First of all THANK YOU for this project. I am based in China and this is really meaningful to me. 

Very glad to hear it! Thanks for saying so :-)

> Full disclosure: I am running my local shell using Bash on Ubuntu on Windows. Also I am running Streisand against an existing linode.

Ok. This is definitely not supported and so I'm not surprised you're running into troubles. I'm hopeful we can make this experience better down the road but for now if you're looking for a smooth experience I recommend running Streisand from a Linux VM and letting it create the Linode instance for you instead of using an existing one.

>  I had another error message but I was able to solve by changing the boot setting to GRUB.

Glad to hear you figured that out. That's one example of a step that is done for you if you let Streisand create the Linode instance which is why I usually recommend that approach :-)

> Next, some questions. If I receive an error message, does that mean that I need to rerun the streisand script from the beginning? or is it partially installed? 

Yes, I would recommend tearing down the server (deleting it from Linode) and starting over. The server will be partially installed and in an inconsistent state.

> On a related note, I am currently rerunning the script only this time without selecting Tor. Is there a way to install just Tor later?

Right now Streisand doesn't support changing existing installations to upgrade, add, or remove services. We recommend creating a brand new Streisand instance every time you run `./streisand`. There are some open feature requests to make migrating data/users between Streisand instances easier since we know this isn't ideal, especially for well-established servers with active users.

> Finally an FYI, running Streisand script takes several hours for me. Not sure if that's related to my Internet connectivity or what, but wanted to bring it to your attention.

Could you add some details about the run time and your internet connection to https://github.com/StreisandEffect/streisand/issues/975 ? Another user in China reports similar (though they are running Streisand over a VPN).

```
 RUNNING HANDLER [tor-bridge : Restart Nginx for the Tor hidden service vhost] ***************************************
fatal: [this is my remote server IP]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service nginx: Failed to start nginx.service: Unit nginx.service is masked.\n"}
```

I haven't seen this error myself - sounds curious! Could you try `systemctl unmask nginx.service && systemctl start nginx.service` and seeing whether that helps?

**Comment by cpu** [comment]
I'm going to close this issue since there hasn't been a response to the questions asked. Thanks!
